.PHONY: help install dev run test \
        up up-build build down logs ps restart \
        db redis infra \
        migrate migration downgrade db-reset \
        env clean

# --- Config -------------------------------------------------------------------

PYTHON ?= python
COMPOSE ?= docker compose
APP_MODULE := app.main:app
UVICORN_HOST ?= 0.0.0.0
UVICORN_PORT ?= 8000

ifeq ($(OS),Windows_NT)
	VENV_BIN := .venv/Scripts
else
	VENV_BIN := .venv/bin
endif

VENV_PYTHON := $(VENV_BIN)/python
VENV_PIP := $(VENV_BIN)/pip
VENV_UVICORN := $(VENV_BIN)/uvicorn
VENV_PYTEST := $(VENV_BIN)/pytest
VENV_ALEMBIC := $(VENV_BIN)/alembic

# --- Help ---------------------------------------------------------------------

help: ## Show available commands
	@echo Usage: make [target]
	@echo.
	@echo Local development:
	@echo   install            Create venv and install runtime dependencies
	@echo   dev                Create venv and install dev + test dependencies
	@echo   env                Copy .env.example to .env when missing
	@echo   run                Run FastAPI with hot reload (local venv)
	@echo   test               Run pytest
	@echo.
	@echo Docker Compose:
	@echo   up                 Start all services (detached)
	@echo   up-build           Build images and start all services
	@echo   build              Build Docker images
	@echo   down               Stop and remove containers
	@echo   logs               Follow container logs
	@echo   ps                 Show running containers
	@echo   restart            Restart all services
	@echo.
	@echo Infrastructure only:
	@echo   db                 Start PostgreSQL only
	@echo   redis              Start Redis only
	@echo   infra              Start PostgreSQL and Redis only
	@echo.
	@echo Database:
	@echo   migrate            Apply all Alembic migrations
	@echo   migration MSG=...  Create autogenerated migration
	@echo   downgrade          Roll back one migration
	@echo   db-reset           Drop DB volume and re-run migrations
	@echo.
	@echo Other:
	@echo   clean              Remove Python __pycache__ directories

# --- Python environment -------------------------------------------------------

install: ## Create venv and install runtime dependencies
	$(PYTHON) -m venv .venv
	$(VENV_PIP) install --upgrade pip
	$(VENV_PIP) install -r requirements.txt

dev: install ## Create venv and install dev + test dependencies
	$(VENV_PIP) install -r requirements-dev.txt

env: ## Copy .env.example to .env when missing
	@$(PYTHON) -c "import pathlib, shutil; p = pathlib.Path('.env'); print('.env already exists') if p.exists() else (shutil.copy('.env.example', '.env'), print('Created .env from .env.example'))"

# --- Local app ----------------------------------------------------------------

run: ## Run FastAPI with hot reload (requires local venv + .env)
	$(VENV_UVICORN) $(APP_MODULE) --reload --host $(UVICORN_HOST) --port $(UVICORN_PORT)

test: ## Run pytest
	$(VENV_PYTEST)

# --- Docker Compose (full stack) ----------------------------------------------

up: ## Start all services (detached)
	$(COMPOSE) up -d

up-build: ## Build images and start all services (detached)
	$(COMPOSE) up --build -d

build: ## Build Docker images
	$(COMPOSE) build

down: ## Stop and remove containers
	$(COMPOSE) down

logs: ## Follow container logs
	$(COMPOSE) logs -f

ps: ## Show running containers
	$(COMPOSE) ps

restart: down up ## Restart all services

# --- Infrastructure only (local dev without app container) ------------------

db: ## Start PostgreSQL only (detached)
	$(COMPOSE) up db -d

redis: ## Start Redis only (detached)
	$(COMPOSE) up redis -d

infra: ## Start PostgreSQL and Redis only (detached)
	$(COMPOSE) up db redis -d

# --- Database migrations ------------------------------------------------------

migrate: ## Apply all Alembic migrations
	$(VENV_ALEMBIC) upgrade head

migration: ## Create migration (usage: make migration MSG="description")
ifndef MSG
	$(error MSG is required. Example: make migration MSG="add users table")
endif
	$(VENV_ALEMBIC) revision --autogenerate -m "$(MSG)"

downgrade: ## Roll back one migration
	$(VENV_ALEMBIC) downgrade -1

db-reset: ## Drop DB volume and re-run migrations (destructive)
	$(COMPOSE) down -v
	$(COMPOSE) up db --wait -d
	$(VENV_ALEMBIC) upgrade head

# --- Cleanup ------------------------------------------------------------------

clean: ## Remove Python cache files
	@$(PYTHON) -c "import pathlib, shutil; [shutil.rmtree(p, ignore_errors=True) for p in pathlib.Path('.').rglob('__pycache__')]"
	@echo Cleaned __pycache__ directories
